package Custom;


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CNS
 */
public class FRONTVIEW extends javax.swing.JFrame {

    /**
     * Creates new form FRONTVIEW
     */
    public FRONTVIEW() {
        initComponents();
    }
    String id;
    String color, armor, hood, bumpers;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("USERCART");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Viner Hand ITC", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FRONT VIEW");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 260, 40));

        jLabel12.setFont(new java.awt.Font("Tunga", 3, 18)); // NOI18N
        jLabel12.setText("Bumpers");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 70, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/sil.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 120, 30));

        jLabel11.setFont(new java.awt.Font("Tunga", 3, 18)); // NOI18N
        jLabel11.setText("Hood Protection");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 110, 30));

        jLabel10.setFont(new java.awt.Font("Tunga", 3, 18)); // NOI18N
        jLabel10.setText("Vehicle colour");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 20));

        jLabel5.setFont(new java.awt.Font("Tunga", 3, 18)); // NOI18N
        jLabel5.setText("Body Armor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/sil.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/sil.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/sil.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 120, 30));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setOpaque(true);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 160, 20));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setOpaque(true);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 100, 20));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setOpaque(true);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 160, 20));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setOpaque(true);
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 120, 20));

        L1.setForeground(new java.awt.Color(255, 255, 255));
        L1.setOpaque(true);
        L1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                L1MousePressed(evt);
            }
        });
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, 20));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setOpaque(true);
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 120, 20));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setOpaque(true);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 120, 20));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setOpaque(true);
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 90, 20));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setOpaque(true);
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 110, 20));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setOpaque(true);
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 100, 20));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setOpaque(true);
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 110, 20));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setOpaque(true);
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel30MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 100, 20));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setOpaque(true);
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 100, 20));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setOpaque(true);
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 100, 20));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setOpaque(true);
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 130, 20));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setOpaque(true);
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 170, 20));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setOpaque(true);
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 150, 20));

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setOpaque(true);
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 130, 20));

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setOpaque(true);
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 160, 20));

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setOpaque(true);
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 100, 20));

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 140, 20));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setOpaque(true);
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 90, 20));

        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setOpaque(true);
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 90, 20));

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setOpaque(true);
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 110, 20));

        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setOpaque(true);
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 100, 20));

        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setOpaque(true);
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 90, 20));

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setOpaque(true);
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 100, 20));

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setOpaque(true);
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 100, 20));

        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 100, 20));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 650, 80));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 650, 80));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 650, 80));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 650, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/frontview.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 670, 460));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/back btn.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/min.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 30, 40));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PICS/exit.png"))); // NOI18N
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 30, 40));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setOpaque(true);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void L1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseClicked
        if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);
    }//GEN-LAST:event_L1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JLabel[][] label = new JLabel[][] {
            {L1, jLabel19, jLabel21, jLabel24, jLabel17, jLabel22, jLabel23},
            {jLabel25, jLabel26, jLabel27, jLabel29, jLabel30, jLabel31, jLabel32},
            {jLabel33, jLabel34, jLabel35, jLabel36, jLabel37, jLabel38, jLabel39},
            {jLabel41, jLabel42, jLabel43, jLabel44, jLabel45, jLabel46, jLabel47}
        };
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","sps");
            Statement stmt=con.createStatement();
            String query="select * from frontview;";
            ResultSet rs=stmt.executeQuery(query);
            rs.first();
            String init = rs.getString(2);
            rs.beforeFirst();
            int i = 0;
            while(rs.next()){
                if (!init.equals(rs.getString(2))) {
                    i = 0;
                    init = rs.getString(2);
                }
                switch (rs.getString(2)) {
                    case "VEHICLE_COLOUR":
                        label[0][i ++].setText(rs.getString(3));
                        break;
                    case "BODY_ARMOR":
                        label[1][i ++].setText(rs.getString(3));
                        break;
                    case "HOOD_PROTECTION":
                        label[2][i ++].setText(rs.getString(3));
                        break;
                    case "BUMPERS":
                        label[3][i ++].setText(rs.getString(3));
                }
            }
            rs.close();
            stmt.close();
            con.close();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        for (JLabel[] x: label) {
            for (JLabel y: x) {
                y.setBackground(Color.black);
                if (y.getText().equals("")) {
                    y.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void L1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MousePressed

    }//GEN-LAST:event_L1MousePressed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseEntered

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
   
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
   if (evt.getComponent().getBackground().equals(Color.blue))
            evt.getComponent().setBackground(Color.black);
        else
            evt.getComponent().setBackground(Color.blue);
        enter((JLabel)evt.getComponent(), true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         USERCART ADD=new USERCART();
         ADD.set(this);
        ADD.setVisible(true);
        ADD.id=id;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
 CHOOSE2 c=new CHOOSE2();
 c.setVisible(true);
 c.id=id;
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        this.setVisible(false);
        new Both.Max(this).setVisible(true);
    }//GEN-LAST:event_jLabel28MouseClicked

    void enter(JLabel evt, boolean b) {
        String name = evt.getText();
        JLabel[][] label = new JLabel[][] {
            {L1, jLabel19, jLabel21, jLabel24, jLabel17, jLabel22, jLabel23},
            {jLabel25, jLabel26, jLabel27, jLabel29, jLabel30, jLabel31, jLabel32},
            {jLabel33, jLabel34, jLabel35, jLabel36, jLabel37, jLabel38, jLabel39},
            {jLabel41, jLabel42, jLabel43, jLabel44, jLabel45, jLabel46, jLabel47}
        };
        try {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/car","root","sps");
            Statement stmt=con.createStatement();
            ResultSet rs = stmt.executeQuery("select count(*) from usercart where subpartsel = '" + name + "' and u_id = \"" + id + "\";");
            rs.first();
            if (rs.getInt("count(*)") != 0) {
                stmt.executeUpdate("delete from usercart where subpartsel ='" + name + "' and u_id = \"" + id + "\";");
            }
            else{
                rs = stmt.executeQuery("select * from frontview where subpart ='" + name + "';");
                rs.first();
                String part = rs.getString("part"), subpart = rs.getString("subpart"), price = rs.getString("price");
                stmt.executeUpdate("insert into usercart values ('" + id + "', '" + part + "', '" + subpart + "', " + price + ");");
            }
        } catch (Exception e) {
        }
        int indexX, indexY;
        loop: for (indexX = 0; indexX < label.length; indexX ++) {
            for (indexY = 0; indexY < label[indexX].length; indexY ++) {
                if (label[indexX][indexY].equals(evt)) break loop;
            }
        }
        if (b) {
            for (JLabel x: label[indexX]) {
                if (x.getBackground().equals(Color.blue) && !x.equals(evt)) {
                    enter(x, false);
                    x.setBackground(Color.black);
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRONTVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRONTVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRONTVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRONTVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRONTVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
