/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IP;

import Both.Pane;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author lab2 admin 12
 */
public class FinalPay extends javax.swing.JFrame {

    /**
     * Creates new form ip8
     */
    
    AccNo a;
    PayMode p;
    
    String cname, name, fname, id, paid;
    int n, ded;
    
    public FinalPay(AccNo a, PayMode p, int n) {
        this.n = n;
        this.a = a;
        this.p = p;
        initComponents();
    }

    private FinalPay() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();
        prc = new javax.swing.JLabel();
        go = new javax.swing.JButton();
        bck = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        blk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txt.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        getContentPane().add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 200, 30));

        prc.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        getContentPane().add(prc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 230, 30));

        go.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/go.PNG"))); // NOI18N
        go.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        getContentPane().add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 110, 80));

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/smbck.jpg"))); // NOI18N
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 900, 490));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back btn.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/min.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, 40));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, -1, 40));

        blk.setBackground(new java.awt.Color(0, 0, 0));
        blk.setOpaque(true);
        getContentPane().add(blk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        String time = "" + java.util.Calendar.getInstance().getTime();
        int bno = 1;
        String car = "";
        
        try{
            Class.forName("java.sql.Driver");
            
            Connection con = DriverManager.getConnection
                ("jdbc:mysql://localhost:3306/project","root","sps");
            
            Statement stmt = con.createStatement();
            
            ResultSet rs = stmt.executeQuery("select b_no from history;");
            rs.last();
            
            if(rs.getRow() > 0)
                bno = rs.getInt("b_no") + 1;
            else
                bno = 1;
            
            if(n == 0)
                car = "New";
            if(n == 1)
                car = "Used";
            
            stmt.executeUpdate("insert into history values(\"" + bno + "\",\"" + id + "\",\""  + name + "\",\"" + time + "\",\"" + car + "\",\"" + cname + "\",\"" + prc.getText() + "\",\"5\",\"" + paid + "\");");
            stmt.executeUpdate("update game set ded = ded + \"" + ded + "\", added = added + 100 where u_id = \"" + id + "\";");
            
            stmt.close();
            rs.close();
            con.close();
            
            Pane p = new Pane(this);
            p.top.setText("Congrats!!You have completed all the steps");
            p.txt.setText("You have received 100 game points.");
            p.yes.setVisible(false);
            p.no.setVisible(false);
            p.setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        Rate r = new Rate(this, n);
        r.setVisible(true);
        r.time = time;
        r.bno.setText("" + bno);
        r.id = id;
        r.name.setText(name);
        r.cname = cname;
        r.car = car;
        r.prc = prc.getText();
        r.fname = fname;
        if(paid.equals("Yes"))
            r.paid = "PAID";
        else if(paid.equals("No"))
            r.paid = "NOT PAID";
        this.dispose();
    }//GEN-LAST:event_goActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        if(a != null)
            a.setVisible(true);
        if(p != null)
            p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setVisible(false);
        new Both.Max(this).setVisible(true);
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalPay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bck;
    private javax.swing.JLabel blk;
    private javax.swing.JLabel exit;
    private javax.swing.JButton go;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel minimize;
    public javax.swing.JLabel prc;
    public javax.swing.JLabel txt;
    // End of variables declaration//GEN-END:variables
}
