/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IP;


import java.sql.*;
import javax.swing.JOptionPane;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author admin
 */
public class Model2 extends javax.swing.JFrame {

    /**
     * Creates new form Model1
     */
    
    rdata dt = new rdata();
    Statement stmt;
    
    UserHome2 u;
    Desc2 d = new Desc2(this);
    
    String brand;
    String model;
    String trans1 = "";
    String oil1 = "";
        
    public Model2(UserHome2 u) {
        this.u = u;
        initComponents();
    }

    private Model2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public String readUsingFiles(String fileName) throws IOException {
        Path path = Paths.get(fileName);
        byte[] bytes = Files.readAllBytes(path);
        @SuppressWarnings("unused")
                List<String> allLines = Files.readAllLines(path, StandardCharsets.UTF_8);
        return (new String(bytes));
    }
    
    public void set (int i) {
        JLabel pic[] = {pic1, pic2, pic3, pic4, pic5, pic6, pic7, pic8, pic9, pic10};
        JLabel name[] = {name1, name2, name3, name4, name5, name6, name7, name8, name9, name10};
        JLabel pr[] = {pr1, pr2, pr3, pr4, pr5, pr6, pr7, pr8, pr9, pr10};
        try{
            String query = "Select transmission, oil_type from " + brand +" where submodel = \"" + name[i].getText() + "\";";
            ResultSet rs = stmt.executeQuery(query);
            rs.first();

            d.trans.setText(rs.getString("transmission"));
            d.oil.setText(rs.getString("oil_type"));
           
            d.fname.setText(fname.getText());
            d.id.setText(id.getText());
            d.name.setText(name[i].getText());
            d.pr.setText(pr[i].getText());
            d.pic.setIcon(pic[i].getIcon());
            d.path.setText(brand + " > " + model + " >");
            d.stmt = stmt;
            String fileName = "D:\\New folder\\" + brand + "\\" + model + "\\" + name[i].getText() + ".txt";
            d.desc.setText(readUsingFiles(fileName));
            d.setVisible(true);
            this.setVisible(false);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        bg2 = new javax.swing.ButtonGroup();
        spanel = new javax.swing.JScrollPane();
        mpanel = new javax.swing.JPanel();
        pic1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        pr1 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        pic2 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        pr2 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        pic3 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        pr3 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        pic4 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        pr4 = new javax.swing.JLabel();
        b4 = new javax.swing.JButton();
        pic5 = new javax.swing.JLabel();
        name5 = new javax.swing.JLabel();
        pr5 = new javax.swing.JLabel();
        b5 = new javax.swing.JButton();
        pic6 = new javax.swing.JLabel();
        name6 = new javax.swing.JLabel();
        pr6 = new javax.swing.JLabel();
        b6 = new javax.swing.JButton();
        pic7 = new javax.swing.JLabel();
        name7 = new javax.swing.JLabel();
        pr7 = new javax.swing.JLabel();
        b7 = new javax.swing.JButton();
        pic8 = new javax.swing.JLabel();
        name8 = new javax.swing.JLabel();
        pr8 = new javax.swing.JLabel();
        b8 = new javax.swing.JButton();
        pic9 = new javax.swing.JLabel();
        name9 = new javax.swing.JLabel();
        pr9 = new javax.swing.JLabel();
        b9 = new javax.swing.JButton();
        pic10 = new javax.swing.JLabel();
        name10 = new javax.swing.JLabel();
        pr10 = new javax.swing.JLabel();
        b10 = new javax.swing.JButton();
        pbck = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        blk = new javax.swing.JLabel();
        bck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 610));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mpanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mpanel.setOpaque(false);
        mpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpanel.add(pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 290, 169));

        name1.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 360, 31));

        pr1.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(pr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 170, 19));

        b1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        b1.setText("Check Details");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        mpanel.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        pic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpanel.add(pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 310, 169));

        name2.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 360, 31));

        pr2.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(pr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 170, 19));

        b2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        b2.setText("Check Details");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        mpanel.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        pic3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpanel.add(pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 290, 169));

        name3.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 360, 31));

        pr3.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(pr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 170, 19));

        b3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        b3.setText("Check Details");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        mpanel.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        pic4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpanel.add(pic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 310, 169));

        name4.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 360, 31));

        pr4.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(pr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 170, 19));

        b4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        b4.setText("Check Details");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        mpanel.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, -1, -1));

        pic5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpanel.add(pic5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 310, 169));

        name5.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 810, 360, 31));

        pr5.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(pr5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 850, 170, 19));

        b5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        b5.setText("Check Details");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        mpanel.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 880, -1, -1));

        pic6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpanel.add(pic6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 630, 290, 169));

        name6.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 810, 360, 31));

        pr6.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(pr6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 850, 170, 19));

        b6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        b6.setText("Check Details");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        mpanel.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 880, -1, -1));

        pic7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpanel.add(pic7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 930, 310, 169));

        name7.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1110, 360, 31));

        pr7.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(pr7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1150, 170, 19));

        b7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        b7.setText("Check Details");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        mpanel.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1180, -1, -1));

        pic8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpanel.add(pic8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 930, 290, 169));

        name8.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(name8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1110, 360, 31));

        pr8.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(pr8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1150, 170, 19));

        b8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        b8.setText("Check Details");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        mpanel.add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 1180, -1, -1));

        pic9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpanel.add(pic9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1240, 310, 169));

        name9.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(name9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1420, 360, 31));

        pr9.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(pr9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1460, 170, 19));

        b9.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        b9.setText("Check Details");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        mpanel.add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1490, -1, -1));

        pic10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mpanel.add(pic10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1240, 310, 169));

        name10.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(name10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1420, 360, 31));

        pr10.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        mpanel.add(pr10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 1460, 170, 19));

        b10.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        b10.setText("Check Details");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        mpanel.add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 1490, -1, -1));

        pbck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pnlbck.jpg"))); // NOI18N
        mpanel.add(pbck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 930));

        spanel.setViewportView(mpanel);

        getContentPane().add(spanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 790, 420));

        fname.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        fname.setText("Login");
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 160, 60));

        id.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        id.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 210, 20));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon.jpg"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 30, 30));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 30, 40));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/min.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 30, 40));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back btn.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        blk.setBackground(new java.awt.Color(0, 0, 0));
        blk.setOpaque(true);
        getContentPane().add(blk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mbck.jpg"))); // NOI18N
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        spanel.getVerticalScrollBar().setUnitIncrement(16);
    }//GEN-LAST:event_formWindowOpened

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        set(0);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        set(1);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        set(2);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        set(3);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        set(4);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        set(5);
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        set(6);
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        set(7);
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        set(8);
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        set(9);
    }//GEN-LAST:event_b10ActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        u.brand.setSelectedItem(brand);
        u.model.setSelectedItem(model);
        u.id.setText(id.getText());
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setVisible(false);
        new Both.Max(this).setVisible(true);        
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Model2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Model2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Model2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Model2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Model2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton b1;
    public javax.swing.JButton b10;
    public javax.swing.JButton b2;
    public javax.swing.JButton b3;
    public javax.swing.JButton b4;
    public javax.swing.JButton b5;
    public javax.swing.JButton b6;
    public javax.swing.JButton b7;
    public javax.swing.JButton b8;
    public javax.swing.JButton b9;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bck;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.ButtonGroup bg2;
    private javax.swing.JLabel blk;
    private javax.swing.JLabel exit;
    public javax.swing.JLabel fname;
    private javax.swing.JLabel icon;
    public javax.swing.JLabel id;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel mpanel;
    public javax.swing.JLabel name1;
    public javax.swing.JLabel name10;
    public javax.swing.JLabel name2;
    public javax.swing.JLabel name3;
    public javax.swing.JLabel name4;
    public javax.swing.JLabel name5;
    public javax.swing.JLabel name6;
    public javax.swing.JLabel name7;
    public javax.swing.JLabel name8;
    public javax.swing.JLabel name9;
    private javax.swing.JLabel pbck;
    public javax.swing.JLabel pic1;
    public javax.swing.JLabel pic10;
    public javax.swing.JLabel pic2;
    public javax.swing.JLabel pic3;
    public javax.swing.JLabel pic4;
    public javax.swing.JLabel pic5;
    public javax.swing.JLabel pic6;
    public javax.swing.JLabel pic7;
    public javax.swing.JLabel pic8;
    public javax.swing.JLabel pic9;
    public javax.swing.JLabel pr1;
    public javax.swing.JLabel pr10;
    public javax.swing.JLabel pr2;
    public javax.swing.JLabel pr3;
    public javax.swing.JLabel pr4;
    public javax.swing.JLabel pr5;
    public javax.swing.JLabel pr6;
    public javax.swing.JLabel pr7;
    public javax.swing.JLabel pr8;
    public javax.swing.JLabel pr9;
    private javax.swing.JScrollPane spanel;
    // End of variables declaration//GEN-END:variables
}
