/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IP;

/**
 *
 * @author lab2 admin 12
 */
public class T_C extends javax.swing.JFrame {

    /**
     * Creates new form T_C
     */
    
    PayMode p;
    
    public T_C(PayMode p) {
        this.p = p;
        initComponents();
    }

    private T_C() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        prc = new javax.swing.JLabel();
        spnl = new javax.swing.JScrollPane();
        t_c = new javax.swing.JTextArea();
        back = new javax.swing.JLabel();
        blk = new javax.swing.JLabel();
        bck = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prc.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        prc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(prc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 700, 40));

        t_c.setEditable(false);
        t_c.setColumns(20);
        t_c.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        t_c.setRows(5);
        t_c.setText("Privacy of your personal information is very important to us. We do not\ndisclose your personal information to third parties for their marketing\npurposes without your explicit consent. Please read this Privacy Policy\nproperly. By purchasing our items you agree with our T&C's.\n\n1. Your Privacy - Our Commitment\nAt Tech Cars, we are extremely proud of our commitment to protect\nyour privacy and the personal information you disclose on the App.\nWe value your trust in us. We will work hard to earn your confidence\nso that you can enthusiastically use our services and recommend us\nto friends and family. Please read the following policy to understand\nhow your personal information will be treated as you make full use of our App.\n\n2. Tech Car's Privacy Guarantee\nTech Cars promises that we will not disclose your personal information\nto third parties for their marketing purposes without your explicit consent.\nFrom time to time we may reveal general statistical information about our App\nand visitors, such as number and type of goods and services purchased, etc.\nYour trust and confidence are our highest priority.\n\n3. Information we collect\nWhen you use our App, we collect and store your personal information\nprovided by you. Our primary goal in doing so is to provide a safe,\nefficient, smooth and customized experience. This allows us to provide\nservices and features that most likely meet your needs. Importantly,\nwe only collect personal information about you that we consider necessary\nfor achieving this purpose. In general, you can browse the App without\ntelling us who you are or revealing any personal information about yourself.\nOnce you give us your personal information, you are not anonymous to us.\nTo fully use our App, you will need to register using our registration form,\nwhere you may be required to provide us with your identity information and\nother personal information as indicated on the form.");
        t_c.setOpaque(false);
        spnl.setViewportView(t_c);

        getContentPane().add(spnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 660, 340));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back btn.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        blk.setBackground(new java.awt.Color(0, 0, 0));
        blk.setOpaque(true);
        getContentPane().add(blk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/smbck.jpg"))); // NOI18N
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        p.setVisible(true);
        p.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        spnl.getVerticalScrollBar().setUnitIncrement(16);
        spnl.getVerticalScrollBar().setValue(0);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T_C.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T_C.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T_C.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T_C.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T_C().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bck;
    private javax.swing.JLabel blk;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel prc;
    private javax.swing.JScrollPane spnl;
    private javax.swing.JTextArea t_c;
    // End of variables declaration//GEN-END:variables
}
