/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gaming;

/**
 *
 * @author Sam'
 */
public class FlappyBird extends javax.swing.JFrame {

    /**
     * Creates new form FlappyBird
     */
    
    Score sc = new Score();
    int i = 0;
    String id, fname;
    
    GamerID g;
        
    public FlappyBird() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blk = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        bck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blk.setBackground(new java.awt.Color(0, 0, 0));
        blk.setOpaque(true);
        getContentPane().add(blk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        f.setBackground(new java.awt.Color(0, 0, 0));
        f.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bird.gif"))); // NOI18N
        f.setOpaque(true);
        getContentPane().add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 20, 20));

        b1.setBackground(new java.awt.Color(0, 153, 0));
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BirdStand.jpg"))); // NOI18N
        b1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 60, 160));

        b2.setBackground(new java.awt.Color(0, 153, 0));
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BirdStand.jpg"))); // NOI18N
        b2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 60, 220));

        b3.setBackground(new java.awt.Color(0, 153, 0));
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BirdStand.jpg"))); // NOI18N
        b3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 60, 250));

        b4.setBackground(new java.awt.Color(0, 153, 0));
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BirdStand.jpg"))); // NOI18N
        b4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 60, 140));

        b5.setBackground(new java.awt.Color(0, 153, 0));
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BirdStand.jpg"))); // NOI18N
        b5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 60, 220));

        b6.setBackground(new java.awt.Color(0, 153, 0));
        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BirdStand.jpg"))); // NOI18N
        b6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b6.setOpaque(true);
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 60, 160));

        b7.setBackground(new java.awt.Color(0, 153, 0));
        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BirdStand.jpg"))); // NOI18N
        b7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b7.setOpaque(true);
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 60, 190));

        b8.setBackground(new java.awt.Color(0, 153, 0));
        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BirdStand.jpg"))); // NOI18N
        b8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        b8.setOpaque(true);
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 60, 190));

        bck.setBackground(new java.awt.Color(102, 255, 0));
        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Birdbck.png"))); // NOI18N
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == 38)
            f.setLocation(f.getX(), f.getY() - 4);
    }//GEN-LAST:event_formKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        sc.setVisible(true);
        
        javax.swing.JFrame x = this;
        x.setVisible(true);
        GameOver go = new GameOver();
        java.util.Timer t = new java.util.Timer();
        
        javax.swing.JLabel lb1[] = {b1, b3, b5, b7};
        javax.swing.JLabel lb2[] = {b2, b4, b6, b8};
        
        t.schedule(new java.util.TimerTask() {
            @Override
            public void run() {
                boolean cd = false;
                javax.swing.JLabel lb[] = {b1, b2, b3, b4, b5, b6, b7, b8};
                for(int n = 0;n < 8;n++){
                    cd = cd || ((f.getY() + f.getHeight()) > lb[n].getY()) && (f.getY() < (lb[n].getY() + lb[n].getHeight())) && ((f.getX() + f.getWidth()) > lb[n].getX()) && (f.getX() < (lb[n].getX() + lb[n].getWidth()));
                }
                sc.score.setText("Score: " + i/100);
                i++;
                
                if (f.getY() < 20 || f.getY() > 510 || cd){
                    t.cancel();
                    sc.dispose();
                    go.name = "Flappy Bird";
                    go.gcode = "sbird";
                    go.score = i/100;
                    go.id = id;
                    go.fname = fname;
                    go.g = g;
                    go.setVisible(true);
                    x.dispose();
                }
                else
                    f.setLocation(f.getX(), f.getY() + 1);
                
                for(int n = 0;n < 4;n++){
                    if(lb1[n].getX() > -60 && lb2[n].getX() > -60){
                        lb1[n].setLocation(lb1[n].getX() - 1, lb1[n].getY());
                        lb2[n].setLocation(lb2[n].getX() - 1, lb2[n].getY());
                    }
                    else{
                        int h = (int) (Math.random() * 200);
                        lb1[n].setBounds(700, lb1[n].getY(), lb1[n].getWidth(), 50 + h);
                        lb2[n].setBounds(700, h + 200, lb2[n].getWidth(), 350 - h);
                    }
                }
            }
        }, 50, 15);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlappyBird.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlappyBird.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlappyBird.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlappyBird.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlappyBird().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel bck;
    private javax.swing.JLabel blk;
    private javax.swing.JLabel f;
    // End of variables declaration//GEN-END:variables
}
