/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gaming;

/**
 *
 * @author Suraj
 */
public class GamerID extends javax.swing.JFrame {

    /**
     * Creates new form GameID
     */
    
    public java.sql.Statement stmt;
    
    StartGame st = new StartGame(this);
    User.UserHome u;
    public GamerID(User.UserHome u) {
        this.u = u;
        initComponents();
    }

    private GamerID() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    void start(String code, char ch){
        st.id = id.getText();
        st.fname = fname.getText();
        st.ch = ch;
        st.gname.setText(code);
        st.img.setIcon(new javax.swing.ImageIcon("D:\\Game\\" + code + "Start.png"));
        st.setVisible(true);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        blk = new javax.swing.JLabel();
        stotal = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        bird = new javax.swing.JLabel();
        apple = new javax.swing.JLabel();
        egg = new javax.swing.JLabel();
        smsg = new javax.swing.JLabel();
        bck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 531));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back btn.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, 40));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/min.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 30, 40));

        blk.setBackground(new java.awt.Color(0, 0, 0));
        blk.setOpaque(true);
        getContentPane().add(blk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        stotal.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        stotal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(stotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 780, 40));

        fname.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 180, 60));

        id.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        id.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 210, 20));

        bird.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BirdGame.png"))); // NOI18N
        bird.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                birdMouseClicked(evt);
            }
        });
        getContentPane().add(bird, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        apple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AppleGame.png"))); // NOI18N
        apple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appleMouseClicked(evt);
            }
        });
        getContentPane().add(apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        egg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EggGame.png"))); // NOI18N
        egg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eggMouseClicked(evt);
            }
        });
        getContentPane().add(egg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        smsg.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        smsg.setForeground(new java.awt.Color(153, 0, 153));
        smsg.setText("Select the one to earn Discount.");
        getContentPane().add(smsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 390, 40));

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gbck.jpg"))); // NOI18N
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        u.setVisible(true);
        u.stmt = stmt;
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setVisible(false);
        new Both.Max(this).setVisible(true);
    }//GEN-LAST:event_minimizeMouseClicked

    private void birdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birdMouseClicked
        start("Flappy Bird",'b');
    }//GEN-LAST:event_birdMouseClicked

    private void appleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appleMouseClicked
        start("Eat The Apple",'a');
    }//GEN-LAST:event_appleMouseClicked

    private void eggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eggMouseClicked
        start("Catch The Egg",'e');
    }//GEN-LAST:event_eggMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamerID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamerID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamerID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamerID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamerID().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apple;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bck;
    private javax.swing.JLabel bird;
    private javax.swing.JLabel blk;
    private javax.swing.JLabel egg;
    private javax.swing.JLabel exit;
    public javax.swing.JLabel fname;
    public javax.swing.JLabel id;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel smsg;
    public javax.swing.JLabel stotal;
    // End of variables declaration//GEN-END:variables
}
