/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gaming;

/**
 *
 * @author Suraj
 */
public class StartGame extends javax.swing.JFrame {

    /**
     * Creates new form StartGame
     */
    
    char ch;
    String id, fname;
    GamerID g;
    public StartGame(GamerID g) {
        this.g = g;
        initComponents();
    }

    StartGame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        blk = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        gname = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        inst = new javax.swing.JPanel();
        m1 = new javax.swing.JLabel();
        m2 = new javax.swing.JLabel();
        bck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back btn.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/min.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 30, 40));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, -1, 40));

        blk.setBackground(new java.awt.Color(0, 0, 0));
        blk.setOpaque(true);
        getContentPane().add(blk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        start.setBackground(new java.awt.Color(255, 255, 255));
        start.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        start.setText("Start Game");
        start.setOpaque(false);
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 120, 30));

        gname.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        gname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(gname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 900, 470));

        inst.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "General Instructions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 10))); // NOI18N
        inst.setOpaque(false);

        m1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        m1.setForeground(new java.awt.Color(153, 0, 153));
        m1.setText("Your simple aim is to cross the obstacles and score as high as you can and earn a great discount.");

        m2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        m2.setForeground(new java.awt.Color(153, 0, 153));
        m2.setText("You can't pause the game in between and if you close the game in between your score wouldn't be updated.");

        javax.swing.GroupLayout instLayout = new javax.swing.GroupLayout(inst);
        inst.setLayout(instLayout);
        instLayout.setHorizontalGroup(
            instLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        instLayout.setVerticalGroup(
            instLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(inst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 880, 100));

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gsbck.jpg"))); // NOI18N
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 900, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setVisible(false);
        new Both.Max(this).setVisible(true);
    }//GEN-LAST:event_minimizeMouseClicked

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        FlappyBird b = new FlappyBird();
        EatTheApple a = new EatTheApple();
        CatchTheEgg e = new CatchTheEgg();
        switch (ch) {
            case 'b':
                b.id = id;
                b.fname = fname;
                b.g = g;
                b.setVisible(true);
                break;
            case 'a':
                a.id = id;
                a.fname = fname;
                a.g = g;
                a.setVisible(true);
                break;
            case 'e':
                e.id = id;
                e.fname = fname;
                e.g = g;
                e.setVisible(true);
                break;
        }
        this.dispose();
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bck;
    private javax.swing.JLabel blk;
    private javax.swing.JLabel exit;
    public javax.swing.JLabel gname;
    public javax.swing.JLabel img;
    private javax.swing.JPanel inst;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m2;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
