/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Both;

/**
 *
 * @author admin
 */
public class FillDetails extends javax.swing.JFrame {

    /**
     * Creates new form Details
     */
    
    java.sql.Statement stmt;
    
    Login lg;
    String code, id;
    char ch;
    int n = 0;
    
    public FillDetails() {
        initComponents();
    }
    
    public void value(String code, char ch, String id){
        this.code = code;
        this.ch = ch;
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fname0 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname0 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        gender0 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        age = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        msg1 = new javax.swing.JLabel();
        msg2 = new javax.swing.JLabel();
        msg3 = new javax.swing.JLabel();
        slider = new javax.swing.JSlider();
        submit = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        white = new javax.swing.JLabel();
        bck = new javax.swing.JLabel();
        blk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 560));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fname0.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        fname0.setForeground(new java.awt.Color(0, 255, 255));
        fname0.setText("First Name:");
        getContentPane().add(fname0, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        fname.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 159, 30));

        lname0.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lname0.setForeground(new java.awt.Color(0, 255, 255));
        lname0.setText("Last Name:");
        getContentPane().add(lname0, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        lname.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 159, 30));

        gender0.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        gender0.setForeground(new java.awt.Color(0, 255, 255));
        gender0.setText("Gender:");
        getContentPane().add(gender0, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 70, -1));

        buttonGroup1.add(male);
        male.setForeground(new java.awt.Color(51, 255, 204));
        male.setText("Male");
        male.setOpaque(false);
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 70, -1));

        buttonGroup1.add(female);
        female.setForeground(new java.awt.Color(51, 255, 204));
        female.setText("Female");
        female.setOpaque(false);
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        age.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        age.setForeground(new java.awt.Color(0, 255, 255));
        age.setText("DOB:");
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 34, 14));

        year.setEditable(false);
        year.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        year.setText("1975");
        year.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yearMouseClicked(evt);
            }
        });
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 60, 30));

        month.setEditable(false);
        month.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        month.setText("1");
        month.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthMouseClicked(evt);
            }
        });
        getContentPane().add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 70, 30));

        date.setEditable(false);
        date.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        date.setText("1");
        date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateMouseClicked(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 50, 30));

        msg1.setForeground(new java.awt.Color(0, 204, 0));
        msg1.setText("Year");
        getContentPane().add(msg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 40, 20));

        msg2.setForeground(new java.awt.Color(0, 204, 0));
        msg2.setText("Month");
        getContentPane().add(msg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 50, 20));

        msg3.setForeground(new java.awt.Color(0, 204, 0));
        msg3.setText("Day");
        getContentPane().add(msg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 40, 20));

        slider.setOpaque(false);
        slider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sliderMouseDragged(evt);
            }
        });
        getContentPane().add(slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 210, -1));

        submit.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        submit.setText("Submit >>");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 160, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 190, 140));

        white.setBackground(new java.awt.Color(255, 255, 255));
        white.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        white.setForeground(new java.awt.Color(102, 51, 255));
        white.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        white.setOpaque(true);
        getContentPane().add(white, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 50));

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GT 500.JPG"))); // NOI18N
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 510));

        blk.setBackground(new java.awt.Color(0, 0, 0));
        blk.setOpaque(true);
        getContentPane().add(blk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        slider.setValue(0);
        slider.setVisible(false);
        month.setEnabled(false);
        date.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        for (char c: fname.getText().toCharArray()){
            if ("0123456789".indexOf(c) > -1) {
                Pane p = new Pane(this);
                p.txt.setText("I think name contains letters.");
                p.yes.setVisible(false);
                p.no.setVisible(false);
                p.setVisible(true);
                return;
            }
        }
        for (char c: lname.getText().toCharArray()){
            if ("0123456789".indexOf(c) > -1) {
                Pane p = new Pane(this);
                p.txt.setText("I think name contains letters.");
                p.yes.setVisible(false);
                p.no.setVisible(false);
                p.setVisible(true);
                return;
            }
        }
        try {
            if(!fname.getText().equals("") && !lname.getText().equals("")){
                char gender = 0;
                if(male.isSelected())
                    gender = 'M';
                if(female.isSelected())
                    gender = 'F';
                String insert = "Update " + code + " set fname = \"" + fname.getText() + "\", lname = \"" + lname.getText() + "\", gender = \"" + gender + "\",DOB = \"" + year.getText() + "/" + month.getText() + "/" + date.getText() + "\" where " + ch +"_id = \"" + id + "\";";
                stmt.executeUpdate(insert);
                lg = new Login(4, null, null, null);
                lg.setVisible(true);
                lg.code = code;
                lg.ch = ch;
                lg.idlb.setText(code+"ID:");
                if(ch == 'a')
                    lg.hmpg.setVisible(false);
                else if(ch == 'u')
                    lg.custadm.setVisible(false);
                this.dispose();
                stmt.close();
                Pane p = new Pane(this);
                if(ch == 'u'){
                    p.top.setText("Your details are successfully saved.");
                    p.txt.setText("Congrats!! You have received 100 game points.");
                }
                else if(ch == 'a'){
                    p.txt.setText("Your details are successfully saved.");
                }
                p.yes.setVisible(false);
                p.no.setVisible(false);
                p.setVisible(true);
            }
            else{
                Pane p = new Pane(this);
                p.txt.setText("You have not entered correct details.");
                p.yes.setVisible(false);
                p.no.setVisible(false);
                p.setVisible(true);
                if (ch == 'a'){
                    p.top.setText("You have not entered correct detais.");
                    p.txt.setText("You do not deserve to be an Admin.");
                    stmt.executeUpdate("Delete from admin where a_id = \"" + id + "\";");
                    System.exit(0);
                }
            }
        }
        catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void yearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearMouseClicked
        n = 1;
        slider.setVisible(true);
        slider.setMinimum(1975);
        slider.setMaximum(2018);
        slider.setValue(Integer.parseInt(year.getText()));
    }//GEN-LAST:event_yearMouseClicked

    private void monthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthMouseClicked
        n = 2;
        slider.setMinimum(1);
        slider.setMaximum(12);
        slider.setValue(Integer.parseInt(month.getText()));
    }//GEN-LAST:event_monthMouseClicked

    private void dateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMouseClicked
        n = 3;
        int a = 31;
        switch (Integer.parseInt(month.getText())){
            case 1: case 3: case 5: case 7: case 8: case 10: case 12:
                a = 31;
                break;
            case 2:
                int y = Integer.parseInt(year.getText());
                if(y % 4 == 0 || y % 400  == 0)
                    a = 29;
                else if(y % 4 != 0 || y % 100  == 0)
                    a = 28;
                break;
            case 4: case 6: case 9: case 11:
                a = 30;
                break;
            default:
                a = 31;
        }
        slider.setMinimum(1);
        slider.setMaximum(a);
        slider.setValue(Integer.parseInt(date.getText()));
    }//GEN-LAST:event_dateMouseClicked

    private void sliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderMouseDragged
        if(n == 1){
            year.setText("" + slider.getValue());
            month.setEnabled(true);
        }
        if(n == 2){
            month.setText("" + slider.getValue());
            date.setEnabled(true);
        }
        if(n == 3){
            date.setText("" + slider.getValue());
        }
    }//GEN-LAST:event_sliderMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FillDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FillDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JLabel bck;
    private javax.swing.JLabel blk;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JTextField date;
    public javax.swing.JRadioButton female;
    public javax.swing.JTextField fname;
    private javax.swing.JLabel fname0;
    private javax.swing.JLabel gender0;
    public javax.swing.JTextField lname;
    private javax.swing.JLabel lname0;
    private javax.swing.JLabel logo;
    public javax.swing.JRadioButton male;
    public javax.swing.JTextField month;
    private javax.swing.JLabel msg1;
    private javax.swing.JLabel msg2;
    private javax.swing.JLabel msg3;
    private javax.swing.JSlider slider;
    private javax.swing.JButton submit;
    public javax.swing.JLabel white;
    public javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
