/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

/**
 *
 * @author admin
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    
    public java.sql.Statement stmt;
    
    int c = 0;
    
    public AdminHome() {
        initComponents();
    }

    public void upd(){
        ChooseCar cc = new ChooseCar();
        cc.setVisible(true);
        cc.fname = fname.getText();
        cc.id = id.getText();
        cc.stmt = stmt;
        this.setVisible(false);
    }
    
    public void dlt(){
        Delete_BM dt = new Delete_BM();
        dt.setVisible(true);
        dt.fname.setText(fname.getText());
        dt.id.setText(id.getText());
        dt.stmt = stmt;
        this.setVisible(false);
    }
    
    public void add(){
        AddCar ac = new AddCar();
        ac.setVisible(true);
        ac.fname.setText(fname.getText());
        ac.id.setText(id.getText());
        ac.stmt = stmt;
        this.setVisible(false);
    }
    
    public void his(){
        History h = new History();
        h.setVisible(true);
        h.fname.setText(fname.getText());
        h.id.setText(id.getText());
        h.stmt = stmt;
        this.setVisible(false);
    }
    
    public void tab(int n){
        javax.swing.JLabel l[] = {update, delete, add, history};
        l[n].setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        for(int i = 0;i < 4;i++){
            if(i != n)
                l[i].setBorder(null);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        update = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        history = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        blk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 470));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Upd txt.png"))); // NOI18N
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        panel.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/D_BM txt.png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        panel.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add txt.png"))); // NOI18N
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        panel.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        history.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/C_His txt.png"))); // NOI18N
        history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyMouseClicked(evt);
            }
        });
        panel.add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N
        panel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        fname.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        fname.setText("Login");
        panel.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 170, 60));

        id.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        panel.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 210, 20));

        logout.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(153, 51, 255));
        logout.setText("Logout");
        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        panel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, 20));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 920, 460));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/min.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, 40));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, 40));

        blk.setBackground(new java.awt.Color(0, 0, 0));
        blk.setOpaque(true);
        getContentPane().add(blk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        panel.setBackground(new java.awt.Color(10 + (int)(Math.random() * 245), 10 + (int)(Math.random() * 245), 10 + (int)(Math.random() * 245)));
        this.setFocusTraversalKeysEnabled(false);
        update.setBorder(null);
        delete.setBorder(null);
        add.setBorder(null);
        history.setBorder(null);
    }//GEN-LAST:event_formWindowOpened

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode() == 9){
            tab(c);
            if(c < 3)
                c++;
            else
                c = 0;
        }
        if(evt.getKeyCode() == 32){
            if(update.getBorder() != null)
                upd();
            else if(delete.getBorder() != null)
                dlt();
            else if(add.getBorder() != null)
                add();
            else if(history.getBorder() != null)
                his();
        }
    }//GEN-LAST:event_formKeyPressed

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        upd();
    }//GEN-LAST:event_updateMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        dlt();
    }//GEN-LAST:event_deleteMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
       add();
    }//GEN-LAST:event_addMouseClicked

    private void historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseClicked
        his();
    }//GEN-LAST:event_historyMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new data.data2().logout(this, "Admin", 'a', stmt);
    }//GEN-LAST:event_logoutMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setVisible(false);
        new Both.Max(this).setVisible(true);
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel blk;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel exit;
    public javax.swing.JLabel fname;
    private javax.swing.JLabel history;
    public javax.swing.JLabel id;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
