/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

/**
 *
 * @author Suraj
 */
public class DeleteCar extends javax.swing.JFrame {

    /**
     * Creates new form DeleteCar
     */
    
    java.sql.Statement stmt;
    
    String brand = null, sub = null;
    String opimg, optxt;
    
    CarDetails c;
    
    public DeleteCar(CarDetails c, String brand, String sub) {
        this.c = c;
        this.brand = brand;
        this.sub = sub;
        initComponents();
    }

    private DeleteCar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void dlt(){
        try {
            String query = "Delete from " + brand + " where submodel = \"" + sub +"\";";
            stmt.executeUpdate(query);
            
            new java.io.File(opimg).delete();
            new java.io.File(optxt).delete();

            c.dispose();
            
            AdminHome ad = new AdminHome();
            ad.setVisible(true);
            ad.stmt = stmt;
            this.dispose();
        }
        catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goback = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        blk = new javax.swing.JLabel();
        bck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Keep Car.png"))); // NOI18N
        goback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackMouseClicked(evt);
            }
        });
        getContentPane().add(goback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 220, 40));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete Car Btn.png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 150, 40));

        name.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        name.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 170, 30));

        blk.setBackground(new java.awt.Color(0, 0, 0));
        blk.setOpaque(true);
        getContentPane().add(blk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 40));

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete Car.png"))); // NOI18N
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 630, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        dlt();
    }//GEN-LAST:event_deleteMouseClicked

    private void gobackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackMouseClicked
        c.setVisible(true);
        c.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_gobackMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setFocusTraversalKeysEnabled(false);
        goback.setBorder(null);
        delete.setBorder(null);
    }//GEN-LAST:event_formWindowOpened

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode() == 9){
            if(goback.getBorder() == null){
                goback.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black, 2));
                delete.setBorder(null);
            }
            else if(delete.getBorder() == null){
                delete.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black, 2));
                goback.setBorder(null);
            }
        }
        if(evt.getKeyCode() == 32){
            if(goback.getBorder() != null){
                c.setVisible(true);
                c.setEnabled(true);
                this.dispose();
            }
            else if(delete.getBorder() != null)
                dlt();
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bck;
    private javax.swing.JLabel blk;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel goback;
    public javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
