/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.io.File;
import javax.swing.DefaultListModel;

/**
 *
 * @author Suraj
 */
public class Delete_BM extends javax.swing.JFrame {

    /**
     * Creates new form Delete_BM
     */
    
    java.sql.Statement stmt;
    
    int n = 0;
    
    public Delete_BM() {
        initComponents();
    }

    public static void recursiveDelete(File file) {
        if (!file.exists())
            return;
        if (file.isDirectory()) {
            for (File f : file.listFiles()) {
                recursiveDelete(f);
            }
        }
        file.delete();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlt = new javax.swing.JLabel();
        pnl2 = new javax.swing.JScrollPane();
        model = new javax.swing.JList<>();
        pnl1 = new javax.swing.JScrollPane();
        brand = new javax.swing.JList<>();
        fname = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        blk = new javax.swing.JLabel();
        bck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dlt brd.png"))); // NOI18N
        dlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dltMouseClicked(evt);
            }
        });
        getContentPane().add(dlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, -1, 60));

        model.setBackground(new java.awt.Color(255, 204, 51));
        model.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Model To Delete", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 0, 10))); // NOI18N
        model.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        model.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        model.setSelectionBackground(new java.awt.Color(0, 0, 0));
        model.setVisibleRowCount(0);
        model.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                modelValueChanged(evt);
            }
        });
        pnl2.setViewportView(model);

        getContentPane().add(pnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 160, 320));

        brand.setBackground(new java.awt.Color(255, 204, 51));
        brand.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Brand To Delete", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 0, 10))); // NOI18N
        brand.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        brand.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        brand.setSelectionBackground(new java.awt.Color(0, 0, 0));
        brand.setVisibleRowCount(0);
        brand.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                brandValueChanged(evt);
            }
        });
        pnl1.setViewportView(brand);

        getContentPane().add(pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, 320));

        fname.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        fname.setText("Login");
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 150, 50));

        id.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 200, 20));

        logout.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(153, 51, 255));
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, 20));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back btn.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/min.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, 40));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 40));

        blk.setBackground(new java.awt.Color(0, 0, 0));
        blk.setOpaque(true);
        getContentPane().add(blk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 40));

        bck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dlt bck.png"))); // NOI18N
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultListModel l = new DefaultListModel();
        l.clear();
        try{
            java.sql.ResultSet rs = stmt.executeQuery(new data.data2().str);

            while(rs.next()){
                String str = rs.getString("Tables_in_project");
                String a = str.substring(0, 1).toUpperCase();
                String b = str.substring(1, str.length());
                l.addElement(a + b);
            }
            brand.setModel(l);
        }
        catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void dltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dltMouseClicked
        Both.Pane p = new Both.Pane(this){
            @Override
            public void method(){
                try{
                    if(n == 1){
                        stmt.executeUpdate("drop table " + brand.getSelectedValue() + ";");
                        recursiveDelete(new File("D:\\Path\\" + brand.getSelectedValue()));
                    }
                    if(n == 2){
                        stmt.executeUpdate("delete from " + brand.getSelectedValue() + " where model =\"" + model.getSelectedValue() +"\";");
                        recursiveDelete(new File("D:\\Path\\" + brand.getSelectedValue() + "\\" + model.getSelectedValue()));
                    }
                } catch (Exception e) {
                    javax.swing.JOptionPane.showMessageDialog(null, e);
                }
                AdminHome ad = new AdminHome();
                ad.setVisible(true);
                ad.fname.setText(fname.getText());
                ad.id.setText(id.getText());
                ad.stmt = stmt;
                f.dispose();
                this.dispose();
            }
        };
        p.txt.setText("Do you really wanna do this?");
        p.ok.setVisible(false);
        p.setVisible(true);
    }//GEN-LAST:event_dltMouseClicked

    private void brandValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_brandValueChanged
        if(brand.getSelectedIndex() > -1){
            n = 1;
            dlt.setIcon(new javax.swing.ImageIcon("D:\\Path\\dlt brd.png"));
            model.clearSelection();

            DefaultListModel l = new DefaultListModel();
            l.clear();
            try {
                String query = "Select distinct model from " + brand.getSelectedValue() + ";";
                java.sql.ResultSet rs = stmt.executeQuery(query);

                while(rs.next()){
                    l.addElement(rs.getString("model"));
                }
                model.setModel(l);
            }
            catch (Exception e){
                javax.swing.JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_brandValueChanged

    private void modelValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_modelValueChanged
        if(brand.getSelectedIndex() > -1){
            n = 2;
            dlt.setIcon(new javax.swing.ImageIcon("D:\\Path\\dlt mdl.png"));
        }
    }//GEN-LAST:event_modelValueChanged

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new data.data2().logout(this, "Admin", 'a', stmt);
    }//GEN-LAST:event_logoutMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        AdminHome ad = new AdminHome();
        ad.setVisible(true);
        ad.fname.setText(fname.getText());
        ad.id.setText(id.getText());
        ad.stmt = stmt;
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setVisible(false);
        new Both.Max(this).setVisible(true);
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_BM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_BM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_BM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_BM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_BM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bck;
    private javax.swing.JLabel blk;
    private javax.swing.JList<String> brand;
    private javax.swing.JLabel dlt;
    private javax.swing.JLabel exit;
    public javax.swing.JLabel fname;
    public javax.swing.JLabel id;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel minimize;
    private javax.swing.JList<String> model;
    private javax.swing.JScrollPane pnl1;
    private javax.swing.JScrollPane pnl2;
    // End of variables declaration//GEN-END:variables
}
