/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Both.Pane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suraj
 */
public class History extends javax.swing.JFrame {

    /**
     * Creates new form History
     */
   
    Statement stmt;
    
    public History() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bno = new javax.swing.JLabel();
        bno0 = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        paid = new javax.swing.JButton();
        scr = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        back = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        blk = new javax.swing.JLabel();
        bck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(bno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 270, 20));

        bno0.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        bno0.setText("Bill No.:");
        getContentPane().add(bno0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 80, 20));

        fname.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        fname.setText("Login");
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 170, 60));

        logout.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(153, 51, 255));
        logout.setText("Logout");
        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, -1, 20));

        id.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 210, 20));

        paid.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        paid.setText("Mark Paid");
        paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidActionPerformed(evt);
            }
        });
        getContentPane().add(paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 150, -1));

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill No", "Buyer ID", "Buyer Name", "Time", "Car Name", "Car Type", "Price", "Rating", "Paid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        tb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbKeyReleased(evt);
            }
        });
        scr.setViewportView(tb);

        getContentPane().add(scr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 960, 270));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back btn.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/min.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, -1, 40));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, -1, 40));

        blk.setBackground(new java.awt.Color(0, 0, 0));
        blk.setOpaque(true);
        getContentPane().add(blk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        bck.setBackground(new java.awt.Color(204, 255, 204));
        bck.setOpaque(true);
        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1000, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        AdminHome ad = new AdminHome();
        ad.setVisible(true);
        ad.fname.setText(fname.getText());
        ad.id.setText(id.getText());
        ad.stmt = stmt;
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setVisible(false);
        new Both.Max(this).setVisible(true);
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new data.data2().logout(this, "Admin", 'a', stmt);
    }//GEN-LAST:event_logoutMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            DefaultTableModel t = (DefaultTableModel)tb.getModel();
            
            ResultSet rs = stmt.executeQuery("select * from history;");
            while(rs.next()){
                t.addRow(new Object[]{rs.getInt("b_no"), rs.getString("u_id"), rs.getString("u_name"), rs.getString("time"), rs.getString("car"), rs.getString("cname"), rs.getInt("prc"), rs.getInt("rating"), rs.getString("paid")});
            }
            rs.close();
        }
        catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        bno.setText("" + tb.getValueAt(tb.getSelectedRow(), 0));
    }//GEN-LAST:event_tbMouseClicked

    private void tbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKeyReleased
        bno.setText("" + tb.getValueAt(tb.getSelectedRow(), 0));
    }//GEN-LAST:event_tbKeyReleased

    private void paidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidActionPerformed
        try{
            if(!bno.getText().equals("")){
                if(tb.getValueAt(tb.getSelectedRow(), 8).equals("No")){
                    stmt.executeUpdate("update history set paid = \"Yes\" where b_no = \"" + bno.getText() + "\";");
                    tb.setValueAt("Yes", tb.getSelectedRow(), 8);
                }
                else{
                    Pane p = new Pane(this);
                    p.txt.setText("It is already paid.");
                    p.yes.setVisible(false);
                    p.no.setVisible(false);
                    p.setVisible(true);
                }
            }
            else{
                Pane p = new Pane(this);
                p.txt.setText("Please select something.");
                p.yes.setVisible(false);
                p.no.setVisible(false);
                p.setVisible(true);
            }
        }
        catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_paidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bck;
    private javax.swing.JLabel blk;
    private javax.swing.JLabel bno;
    private javax.swing.JLabel bno0;
    private javax.swing.JLabel exit;
    public javax.swing.JLabel fname;
    public javax.swing.JLabel id;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton paid;
    private javax.swing.JScrollPane scr;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
